name: My first Workflow

on: [push]

jobs:
    say-hello:
      runs-on: ubuntu-latest
      steps:
        - name: Say Hello
          run: echo 'Hello world!'
         
    build-and-test:
      needs: [say-hello]
      runs-on: ubuntu-latest
      steps:
          - name: Checkout out this repo
            uses: actions/checkout@v3

          - name: Install dependencies
            run: sudo apt install build-essential -y 

          - name: Install Python
            run: sudo apt install pyhton3 -y

          - run: pwd

          - name: Run test
            run: python3 test.py

      
